services:
  # Override API service for development
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debug port
    volumes:
      - .:/app
      - /app/node_modules
      - /app/generated
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - DATABASE_URL=mysql://root:123456@capstone-mysql:3306/capstone_fiverr
    command: npm run start:dev
    stdin_open: true
    tty: true

  # Override MySQL for development
  mysql:
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=capstone_fiverr
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_dev_data:
    driver: local
