services:
  BE:
    build: .
    container_name: con-be_capstone-api-Fiverr
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - DB
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  DB:
    image: mysql:8.0
    container_name: con-db_capstone-api-Fiverr
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=capstone_fiverr
      - MYSQL_USER=capstone_user
      - MYSQL_PASSWORD=capstone_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: unless-stopped

volumes:
  mysql_data:
