services:
  db:
    image: mysql:8.0
    container_name: capstone_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=capstone_fiverr
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build: .
    container_name: capstone_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:123456@db:3306/capstone_fiverr
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  db_data:
