services:
  BE:
    image: khanh2nq/img-be_api_fiverr:latest
    container_name: con-be_api_fiverr
    ports:
      - 3070:3069
    env_file:
      - .env
    depends_on:
      - DB

  DB:
    image: mysql:8.0
    container_name: con-db_api_fiverr
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
