services:
  BE:
    image: khanh2nq/img-be_capstone-api-fiverr:latest
    container_name: capstone-backend
    ports:
      - 3070:3069
    env_file:
      - .env
    depends_on:
      - DB

  DB:
    image: mysql:8.0
    container_name: capstone-database
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    