name: production
url: https://api.capstone-fiverr.com
protection_rules:
  - required_reviewers:
      teams: [dev-team, qa-team, devops-team]
    required_status_checks:
      strict: true
      contexts:
        - "CI - Build & Test"
        - "Security & Dependencies"
        - "Docker Registry"
        - "CD - Deploy to Staging"
    enforce_admins: true
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
    required_conversation_resolution: true
    required_linear_history: true
    required_signatures: true
    lock_branch: false
    allow_fork_syncing: false
