# ========================================
# PRODUCTION ENVIRONMENT CONFIGURATION
# ========================================

# Environment name
name: production

# Environment URL (for deployment status)
url: https://your-domain.com

# Branch protection rules
protection_rules:
  # Required reviewers
  required_reviewers:
    - username: your-username
      type: USER
    - team: senior-developers
      type: TEAM
    - team: devops
      type: TEAM
  
  # Required status checks
  required_status_checks:
    strict: true
    contexts:
      - "CI - Build & Test"
      - "Lint & Format Check"
      - "Unit Tests"
      - "Build Check"
      - "Security Scan"
      - "Docker Build Test"
      - "Deploy to Staging"
  
  # Branch restrictions
  restrictions:
    users: []
    teams: []
    apps: []
  
  # Enforce admins
  enforce_admins: true
  
  # Allow force pushes
  allow_force_pushes: false
  
  # Allow deletions
  allow_deletions: false
  
  # Required conversation resolution
  required_conversation_resolution: true
  
  # Required linear history
  required_linear_history: true
  
  # Dismiss stale reviews
  dismiss_stale_reviews: true
  
  # Require code owner reviews
  require_code_owner_reviews: true
  
  # Required approving reviews count
  required_approving_review_count: 2
  
  # Require last push approval
  require_last_push_approval: true
  
  # Restrict pushes that create files
  restrict_pushes:
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
  
  # Required deployments
  required_deployments:
    - environment: staging
      required_reviewers:
        - username: your-username
          type: USER
        - team: senior-developers
          type: TEAM
