name: staging
url: https://staging-api.capstone-fiverr.com
protection_rules:
  - required_reviewers:
      teams: [dev-team, qa-team]
    required_status_checks:
      strict: true
      contexts:
        - "CI - Build & Test"
        - "Security & Dependencies"
        - "Docker Registry"
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
    required_conversation_resolution: true
    required_linear_history: false
    required_signatures: false
    lock_branch: false
    allow_fork_syncing: false
