name: CI

on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: api_fiverr

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t khanh2nq/img-be_api_fiverr:${{ github.sha }} .

      - name: Push Docker image
        run: docker push khanh2nq/img-be_api_fiverr:${{ github.sha }}

      - name: Verify image pushed
        run: |
          echo "✅ Image successfully pushed to Docker Hub"
          echo "Image: khanh2nq/img-be_api_fiverr:${{ github.sha }}"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"


  
  