name: Database Migration

on:
  workflow_run:
    workflows: ['CI - Build and Push Docker Image']
    types:
      - completed
    branches: ['main']

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest image
        run: docker pull khanh2nq/img-be_api_fiverr:latest

      - name: Create environment file
        run: |
          cat > .env << EOF
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
          PORT=3069
          NODE_ENV=production
          EOF

      - name: Run database migrations
        run: |
          docker run --rm \
            --env-file .env \
            khanh2nq/img-be_api_fiverr:latest \
            npx prisma migrate deploy

      - name: Cleanup
        run: rm -f .env
